### ISSUE TITLE
CUDA not found

### ISSUE THREAD

**Issue by Th3EvilGod** [rudymohammadbali/OpenAI-Whisper-GUI#12]
I get CUDA not found error but i have installed it with pip install cuda-python
the software doesnt see the GPU, in options there is only the CPU. Any suggestion on fix?

**Comment by iamironman0** [comment]
Try this:

`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

If not worked, then try this:

Clean reinstall, remove pytorch and use setup.py to install all packages.

**Comment by Th3EvilGod** [comment]
1. removed pytorch with `pip uninstall torch torchvision torchaudio`
2. `python setup.py`
3. still getting the same error
![image](https://github.com/iamironman0/OpenAI-Whisper-GUI/assets/117441689/28feb1df-4a14-4583-9dfb-e1598f8b72a9)

**Comment by iamironman0** [comment]
Hmm, there's a settings.json file you can try set cuda to True, and check if it works.

And yes you can use Whisper Transcriber. The only difference is that Whisper Transcriber has more tools and better version of OpenAI Whisper GUI.

**Comment by Th3EvilGod** [comment]
> Hmm, there's a settings.json file you can try set cuda to True, and check if it works.
> 
> And yes you can use Whisper Transcriber. The only difference is that Whisper Transcriber has more tools and better version of OpenAI Whisper GUI.

There is no setting.json file. I have also checked Whisper Transcriber but it also doesnt work due to error. I have reported it as an issue.

**Comment by Rockyzsu** [comment]
same with me in CPU mechine

**Comment by rudymohammadbali** [comment]
> same with me in CPU mechine

Will check on issues very soon!

**Comment by rudymohammadbali** [comment]
@Th3EvilGod , @Rockyzsu 

### **version 1.0.0 has been released. all issues has been fixed!**
